### ISSUE TITLE
Cannot build with system Lua 5.5 installed

### ISSUE THREAD

**Issue by ccoors** [pinguin999/ALPACA#22]
I get this error when attempting to build the project. Apparently it attempts to include `lua.hpp`, but the bundled Lua 5.4 (`subprojects/schnacker/subprojects/lua`) does not generate it, so it attempts to use my system Lua (5.5.1).

It does not happen when just building `schnacker` independently, so I'm creating the issue here.

```
In file included from .../ALPACA/subprojects/schnacker/subprojects/sol2/include/sol/compatibility.hpp:46,
                 from .../ALPACA/subprojects/schnacker/subprojects/sol2/include/sol/bytecode.hpp:27,
                 from .../ALPACA/subprojects/schnacker/subprojects/sol2/include/sol/sol.hpp:51,
                 from .../ALPACA/subprojects/schnacker/src/schnacker.hpp:15,
                 from .../ALPACA/subprojects/schnacker/src/stepresults.cpp:1:
.../ALPACA/subprojects/schnacker/subprojects/sol2/include/sol/compatibility/compat-5.3.h:410:4: error: #error "unsupported Lua version (i.e. not Lua 5.1, 5.2, 5.3, or 5.4)"
  410 | #  error "unsupported Lua version (i.e. not Lua 5.1, 5.2, 5.3, or 5.4)"
      |    ^~~~~
```

Possible fix: add `add_compile_definitions(SOL_NO_LUA_HPP=1)` to `CMakeLists.txt`

**Comment by pinguin999** [comment]
Yes, we have the same Issue. 
We switched sol2 to this fork https://github.com/halx99/sol2/tree/support-lua-5.5 at the moment. 

Did the possible fix worked for you?

**Comment by ccoors** [comment]
Yes, the workaround fixes the issue for me. Removing it now leads to a segmentation fault at runtime instead.
